spring.datasource.url=jdbc:postgresql://localhost:5432/TGBot
spring.datasource.username=UserTGBot
spring.datasource.password=UserTGBot
telegram.bot.token=8491328514:AAHKBfBh3via6ZQhqH7tnx-FFQ81Kfyf5aY

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yml

