spring.datasource.url=jdbc:postgresql://localhost:5432/TGBot
spring.datasource.username=UserTGBot
spring.datasource.password=UserTGBot
telegram.bot.token=8491328514:AAHKBfBh3via6ZQhqH7tnx-FFQ81Kfyf5aY
